#!/usr/bin/env bash
#
# syntax screenshot.sh local fullscreen

if [ $1 == "1" ]; then
    filename=$HOME/Pictures/$(date "+%Y-%m-%d_%H%M%S").png
    if [ $2 == "1" ]; then
        grim -c $filename
    else
        grim -c -g "$(slurp)" $filename
    fi
    notify-send -t 2000 "Screenshot taken!"
    exit 0
else
    if [ $2 == "1" ]; then
        grim -c /tmp/screenshot.png
    else
        grim -c -g "$(slurp)" /tmp/screenshot.png
    fi
fi
if [[ $? == 1 ]]; then exit 1; fi
notify-send -t 2000 "Screenshot taken, uploading..."

# URL to uplaod to
url="https://0x0.st"

curl -F "file=@/tmp/screenshot.png" $url | wl-copy
notify-send "Screenshot uploaded!"
rm /tmp/screenshot.png
