#! /bin/sh

########################################################################
## Autostart
########################################################################
$HOME/.config/bspwm/autostart.sh
########################################################################

########################################################################
## Start Hotkeys
########################################################################
pgrep -x sxhkd > /dev/null || sxhkd &
########################################################################

########################################################################
## BSPWM Settings
########################################################################
bspc monitor -d I II III

bspc config border_width            3
bspc config top_padding            40
bspc config left_padding           10
bspc config right_padding          10
bspc config window_gap              6

bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config paddless_monocle    false

bspc rule -a firefox desktop='^2' state=monocle follow=on
bspc rule -a Gimp-2.10 desktop='^2' state=monocle follow=on
bspc rule -a Steam desktop='^2' state=monocle follow=on
bspc rule -a Steam desktop='^1' follow=on

# Use pywal color
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
########################################################################
