# Author : Devin Singh <drsingh2518@icloud.com>
# A port of the mix palette from gruvbox material. https://github.com/sainnhe/gruvbox-material

"attribute" = { fg = "purple" }
"keyword" = { fg = "red" }
"keyword.directive" = { fg = "purple", modifiers = ["italic"] }
"keyword.operator" = { fg = "orange" }
"namespace" = { fg = "yellow", modifiers = ["italic"] }
"punctuation" = { fg = "fg0" }
"punctuation.delimiter" = { fg = "grey1" }
"punctuation.special" = { fg = "blue" }
"operator" = { fg = "orange" }
"special" = { fg = "yellow" }
"property" = { fg = "green" }
"variable" = { fg = "fg0" }
"variable.property" = { fg = "green" }
"variable.builtin" = { fg = "blue", modifiers = ["italic"] }
"type" = { fg = "yellow" }
"type.builtin" = { fg = "yellow", modifiers = ["italic"]}
"constructor" = { fg = "green", modifiers = ["bold"] }
"function" = { fg = "green", modifiers = ["bold"] }
"function.macro" = { fg = "green", modifiers = ["bold"] }
"function.builtin" = { fg = "green", modifiers = ["bold"] }
"comment" = { fg = "gray1", modifiers = ["italic"]  }
"constant" = { fg = "fg0" }
"constant.builtin" = { fg = "fg0" }
"string" = "aqua"
"number" = "purple"
"escape" = { fg = "green" }
"label" = "orange"
"module" = "purple"

"warning" = { bg = "bg_visual_yellow", modifiers = ["underline"] }
"error" = { bg = "bg_visual_red", modifiers = ["underlined"] }
"info" = { bg = "bg_visual_blue", modifiers = ["underlined"] }
"hint" = { bg = "bg_visual_green", modifiers = ["underlined"] }

"ui.background" = { fg = "fg0", bg = "bg0" }
"ui.linenr" = { fg = "bg5" }
"ui.linenr.selected" = { fg = "grey1" }
"ui.statusline" = { fg = "grey2", bg = "bg_statusline2" }
"ui.statusline.inactive" = { fg = "grey1", bg = "bg_statusline1" }

"ui.cursor.match" = { bg = "bg4" }
"ui.menu" = { fg = "fg1", bg = "bg3" }
"ui.menu.selected" = { fg = "bg3", bg = "grey1" }
# ????????
"ui.popup" = { bg = "bg1" }
"ui.window" = { bg = "bg1" }
"ui.help" = { bg = "bg1", fg = "fg1" }
"ui.text" = { fg = "fg1" }
"ui.text.focus" = { fg = "fg1" }
"ui.selection" = { bg = "bg3", modifiers = ["reversed"] }
"ui.cursor.primary" = { modifiers = ["reversed"] }

"diagnostic" = { modifiers = ["underlined"] }

[palette]
# Palette 1
bg0 = "#1d2021"
bg1 = "#282828"
bg2 = "#282828"
bg3 = "#3c3836"
bg4 = "#3c3836"
bg5 = "#504945"
bg_statusline1 = "#282828"
bg_statusline2 = "#32302f"
bg_statusline3 = "#504945"
bg_diff_green = "#32361a"
bg_visual_green = "#333e34"
bg_diff_red = "#3c1f1e"
bg_visual_red = "#442e2d"
bg_diff_blue = "#0d3138"
bg_visual_blue = "#2e3b3b"
bg_visual_yellow = "#473c29"
bg_current_word = "#32302f"

# Palette 2
fg0 = "#e2cca9"
fg1 = "#e2cca9"
red = "#f2594b"
orange = "#f28534"
yellow = "#e9b143"
green = "#b0b846"
aqua = "#8bba7f"
blue = "#80aa9e"
purple = "#d3869b"
bg_red = "#db4740"
bg_green = "#b0b846"
bg_yellow = "#e9b143"

# Palette 3
grey0 = "#7c6f64"
grey1 = "#928374"
grey2 = "#a89984"
